name: functions workflow

on:
    pull_request:
    workflow_dispatch:

jobs:
    run_functions:
        runs-on: ubuntu-latest
        steps:
            - name: success step
              run: echo "Hello world"
            - name: I will be excuted
              if: ${{success()}}
              run: echo "I will print if previous steps succed"
            - name: I will be skipped
              if: ${{failure()}}
              run: echo "I will print if previous steps fail"
            - name: workflow excution on success
              if: ${{!cancelled()}}
              run: echo "I will always print if the workflow is not cancelled"
            - name: cancel excution
              if: ${{cancelled()}}
              run: echo "I will  print if the workflow cancel"
